const roadLevelStartPoints = [
    {
        levelStartX: 50,
        levelStartY: 0
    },
    {
        levelStartX: 900,
        levelStartY: 0
    },
    {
        levelStartX: 500,
        levelStartY: 0
    },
    {
        levelStartX: 0,
        levelStartY: 0
    },
    {
        levelStartX: 700,
        levelStartY: 0
    },
    {
        levelStartX: 200,
        levelStartY: 0
    }
]

const startMoney = [600, 1500, 2200, 3000, 5000, 5000];

const levelInformation = [
    {
        title: "Are you ready for the first level?",
        monsterTitle: "SMALL BUG",
        monsterParagraph: "Small bugs occur regularly, luckily they are easy to eliminate.",
        didYouKnow: "Did you know?",
        didYouKnowParagraph: "Did you know that you can de-select a gun by pressing ESCAPE.",
        monsterImg: './images/basic.png'
    },
    {
        title: "Good Start! But you have along way to go.",
        monsterTitle: "LIGHTNING FAST BUG",
        monsterParagraph: "Be careful! Those bugs will move faster if they receive damage.",
        didYouKnow: "Did you know?",
        didYouKnowParagraph: "That you can select guns by pressing your arrow keys.",
        monsterImg: './images/speed.png'
    },
    {
        title: "You are on a roll! Keep it up!",
        monsterTitle: "MEDIC BUG",
        monsterParagraph: "Those bugs care about their fellow bugs. They heal them.",
        didYouKnow: "Did you know?",
        didYouKnowParagraph: "That you can put Gandalf on the road.",
        monsterImg: './images/heal.png'
    },
    {
        title: "This will be hard one.",
        monsterTitle: "HUGE BUG",
        monsterParagraph: "Those Bugs are huge, do you have enough firepower?",
        didYouKnow: "Did you know?",
        didYouKnowParagraph: "Did you know that a bazooka deals splash damage.",
        monsterImg: './images/big.png'
    },
    {
        title: "You are great at this!",
        monsterTitle: "NINJA BUG",
        monsterParagraph: "These are tricky bugs! They might become invisible.",
        didYouKnow: "Did you know?",
        didYouKnowParagraph: "Did you know that you're outperforming 95% of the players.",
        monsterImg: './images/ninja.png'
    },
    {
        title: "The final level",
        monsterTitle: "FLYING BUG",
        monsterParagraph: "Those bugs will not follow the roads. They Fly!",
        didYouKnow: "Did you know?",
        didYouKnowParagraph: "Did you that you're at the final level? Good luck!",
        monsterImg: './images/flying.png'
    }
]

const roadLevels = [
    [
        {
            startX: 50,
            startY: 0,
            width: 50,
            height: 200,
            collisionSide: 'bottom',
            directionChangeX: 1,
            directionChangeY: 0,
            color: 'blue'
        }, 
        {
            startX: 100,
            startY: 150,
            width: 250,
            height: 50,
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: -1,
        }, 
        {
            startX: 300,
            startY: 50,
            width: 50,
            height: 100,
            collisionSide: 'top',
            directionChangeX: 1,
            directionChangeY: 0,
        }, 
        {
            startX: 350,
            startY: 50,
            width: 600,
            height: 50,
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: 1,
        }, 
        {
            startX: 900,
            startY: 100,
            width: 50,
            height: 350,
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        }, 
        {
            startX: 650,
            startY: 400,
            width: 250,
            height: 50,
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: -1,
        }, 
        {
            startX: 650,
            startY: 200,
            width: 50,
            height: 200,
            collisionSide: 'top',
            directionChangeX: -1,
            directionChangeY: 0,
        },         
        {
            startX: 500,
            startY: 200,
            width: 150,
            height: 50,
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: 1,
        },
        {
            startX: 500,
            startY: 250,
            width: 50,
            height: 200,
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        },
        {
            startX: 300,
            startY: 400,
            width: 200,
            height: 50,
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: -1,
        },
        {
            startX: 300,
            startY: 300,
            width: 50,
            height: 100,
            collisionSide: 'top',
            directionChangeX: -1,
            directionChangeY: 0,
        },
        {
            startX: 50,
            startY: 300,
            width: 250,
            height: 50,
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: 1,
        },
        {
            startX: 50,
            startY: 350,
            width: 50,
            height: 150,
            collisionSide: 'bottom',
            directionChangeX: 0,
            directionChangeY: 1,
        }   
    ],
    [
        {
            startX: 900,
            startY: 0,
            width: 50,
            height: 500, // test if I can set this to 450
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        }, 
        {
            startX: 750,
            startY: 450,
            width: 150,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: -1,
        }, 
        {
            startX: 750,
            startY: 0,
            width: 50,
            height: 450, 
            collisionSide: 'top',
            directionChangeX: -1,
            directionChangeY: 0,
        }, 
        {
            startX: 250,
            startY: 0,
            width: 500,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: 1,
        }, 
        {
            startX: 250,
            startY: 50,
            width: 50,
            height: 400, 
            collisionSide: 'bottom',
            directionChangeX: 1,
            directionChangeY: 0,
        }, 
        {
            startX: 300,
            startY: 400,
            width: 350,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: -1,
        }, 
        {
            startX: 600,
            startY: 100,
            width: 50,
            height: 300, 
            collisionSide: 'top',
            directionChangeX: -1,
            directionChangeY: 0,
        }, 
        {
            startX: 350,
            startY: 100,
            width: 250,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: 1,
        }, 
        {
            startX: 350,
            startY: 150,
            width: 50,
            height: 200, 
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        }, 
        {
            startX: 100,
            startY: 300,
            width: 250,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: 1,
        }, 
        {
            startX: 100,
            startY: 350,
            width: 50,
            height: 150, 
            collisionSide: 'bottom',
            directionChangeX: 0,
            directionChangeY: 1,
        }, 
    ],
    [
        {
            startX: 500,
            startY: 0,
            width: 50,
            height: 150, 
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        }, 
        {
            startX: 50,
            startY: 100,
            width: 500,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: 1,
        },  
        {
            startX: 50,
            startY: 150,
            width: 50,
            height: 300, 
            collisionSide: 'bottom',
            directionChangeX: 1,
            directionChangeY: 0,
        },   
        {
            startX: 100,
            startY: 400,
            width: 350,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
        {
            startX: 400,
            startY: 200,
            width: 50,
            height: 200, 
            collisionSide: 'top',
            directionChangeX: 1,
            directionChangeY: 0,
        },   
        {
            startX: 450,
            startY: 200,
            width: 200,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
        {
            startX: 600,
            startY: 50,
            width: 50,
            height: 150, 
            collisionSide: 'top',
            directionChangeX: 1,
            directionChangeY: 0,
        },   
        {
            startX: 650,
            startY: 50,
            width: 300,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: 1,
        },   
        {
            startX: 900,
            startY: 100,
            width: 50,
            height: 300, 
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        },   
        {
            startX: 500,
            startY: 350,
            width: 400,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: 1,
        },   
        {
            startX: 500,
            startY: 350,
            width: 50,
            height: 200, 
            collisionSide: 'bottom',
            directionChangeX: 0,
            directionChangeY: 1,
        }
    ], 
    [
        {
            startX: 0,
            startY: 0,
            width: 50,
            height: 200, 
            collisionSide: 'bottom',
            directionChangeX: 1,
            directionChangeY: 0,
        },   
        {
            startX: 50,
            startY: 150,
            width: 200,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
        {
            startX: 200,
            startY: 0,
            width: 50,
            height: 150, 
            collisionSide: 'top',
            directionChangeX: 1,
            directionChangeY: 0,
        },   
        {
            startX: 250,
            startY: 0,
            width: 750,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: 1,
        },   
        {
            startX: 950,
            startY: 50,
            width: 50,
            height: 450, 
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        },   
        {
            startX: 300,
            startY: 450,
            width: 650,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
        {
            startX: 300,
            startY: 150,
            width: 50,
            height: 300, 
            collisionSide: 'top',
            directionChangeX: 1,
            directionChangeY: 0,
        },   
        {
            startX: 350,
            startY: 150,
            width: 550,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: 1,
        },   
        {
            startX: 850,
            startY: 200,
            width: 50,
            height: 200, 
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        },   
        {
            startX: 400,
            startY: 350,
            width: 450,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
        {
            startX: 400,
            startY: 250,
            width: 50,
            height: 100, 
            collisionSide: 'top',
            directionChangeX: 1,
            directionChangeY: 0,
        },   
        {
            startX: 450,
            startY: 250,
            width: 350,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: 1,
        },   
        {
            startX: 750,
            startY: 300,
            width: 50,
            height: 300, 
            collisionSide: 'bottom',
            directionChangeX: 0,
            directionChangeY: -1,
        }  
    ],
    [
        {
            startX: 700,
            startY: 0,
            width: 50,
            height: 250, 
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        },   
        {
            startX: 450,
            startY: 200,
            width: 250,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
        {
            startX: 450,
            startY: 100,
            width: 50,
            height: 100, 
            collisionSide: 'top',
            directionChangeX: 1,
            directionChangeY: 0,
        },   
        {
            startX: 500,
            startY: 100,
            width: 400,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: 1,
        },   
        {
            startX: 850,
            startY: 150,
            width: 50,
            height: 300, 
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        },   
        {
            startX: 200,
            startY: 400,
            width: 650,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
        {
            startX: 200,
            startY: 50,
            width: 50,
            height: 350, 
            collisionSide: 'top',
            directionChangeX: 1,
            directionChangeY: 0,
        },  
        {
            startX: 250,
            startY: 50,
            width: 150,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: 1,
        },    
        {
            startX: 350,
            startY: 100,
            width: 50,
            height: 150, 
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        },   
        {
            startX: 50,
            startY: 200,
            width: 300,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: 1,
        },   
        {
            startX: 50,
            startY: 250,
            width: 50,
            height: 350, 
            collisionSide: 'bottom',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
    ],
    [
        {
            startX: 200,
            startY: 0,
            width: 50,
            height: 350, 
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        },   
        {
            startX: 0,
            startY: 300,
            width: 200,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
        {
            startX: 0,
            startY: 100,
            width: 50,
            height: 200, 
            collisionSide: 'top',
            directionChangeX: 1,
            directionChangeY: 0,
        },   
        {
            startX: 50,
            startY: 100,
            width: 950,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: 1,
        },   
        {
            startX: 950,
            startY: 150,
            width: 50,
            height: 200, 
            collisionSide: 'bottom',
            directionChangeX: -1,
            directionChangeY: 0,
        },   
        {
            startX: 750,
            startY: 300,
            width: 200,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
        {
            startX: 750,
            startY: 0,
            width: 50,
            height: 600, 
            collisionSide: 'top',
            directionChangeX: -1,
            directionChangeY: 0,
        },   
        {
            startX: 300,
            startY: 0,
            width: 450,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: 1,
        },   
        {
            startX: 300,
            startY: 50,
            width: 50,
            height: 350, 
            collisionSide: 'bottom',
            directionChangeX: 1,
            directionChangeY: 0,
        },   
        {
            startX: 350,
            startY: 350,
            width: 350,
            height: 50, 
            collisionSide: 'right',
            directionChangeX: 0,
            directionChangeY: -1,
        },   
        {
            startX: 650,
            startY: 200,
            width: 50,
            height: 150, 
            collisionSide: 'top',
            directionChangeX: -1,
            directionChangeY: 0,
        },   
        {
            startX: 450,
            startY: 200,
            width: 200,
            height: 50, 
            collisionSide: 'left',
            directionChangeX: 0,
            directionChangeY: 1,
        },   
        {
            startX: 450,
            startY: 250,
            width: 50,
            height: 400, 
            collisionSide: 'bottom',
            directionChangeX: 0,
            directionChangeY: -1,
        }   
    ]
]
